#!/bin/sh

#abort on error
set -e

optionsPrep=('splitBam' 'prepBam' 'prepPr' 'prepEnh' 'prepHiC')

optionsDNase=('genIndex' 'bamToArray' 'pgenProfile' 'egenProfile')
numArrayDNase=(30 700 30 30)

optionsDNA=('pDNA' 'eDNA')

optionsPCHiC=('hicMatch' 'hicLabels' 'selectDNase' 'selectDNA')
cellList=('tB' 'tCD4' 'nCD4' 'FoeT' 'Mon' 'tCD8')

function usage
{
    echo "usage: scriptMain [-n AN_ARG || -c SOME_MORE_ARGS || -h] task_type"
    echo "   ";
    echo "  -n | --num-tasks    : number of sub-tasks";
    echo "  -c | --cell         : cell type";
    echo "  -h | --help         : This message";
    exit 0
}

function parse_args
{
  # positional args
  args=()

  # named args
  while [ "$1" != "" ]; do
      case "$1" in
          -n | --num-tasks )       num_tasks="$2";      shift;;
          -c | --cell )                 cell="$2";      shift;;
          -h | --help )                 usage;                   exit;; # quit and show usage
          * )                           args+=("$1")             # if no match, add it to the positional args
      esac
      shift # move to next kv pair
  done

  # restore positional args
  set -- "${args[@]}"

  # set positionals to vars
  option="${args[0]}"

  # only one positional argument required
  if [[ $# -gt 1 ]]; then
    usage
  fi

}


function run
{

  parse_args "$@"

  if [[ ${optionsDNase[@]} == *$option* && -z "$num_tasks" ]]; then
    for i in "${!optionsDNase[@]}"; do
       if [[ "${optionsDNase[$i]}" = "${option}" ]]; then
          sbatchopt="-a 0-${numArrayDNase[$i]} "
       fi
    done
  elif [[ -n "$num_tasks" ]]; then
    sbatchopt="-a 0-${num_tasks} "
  fi

  if [[ -n "$cell" ]]; then
    cellList=(${cell})
  fi

  if [[ ${optionsPrep[@]} == *$option* ]]; then
    echo "sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option}"
    sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option}
  elif [[ ${optionsDNase[@]:1} == *$option* ]]; then
    echo "sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option}"
    sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option}
  elif [[ ${optionsDNA[@]} == *$option* ]]; then
    echo "sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option}"
    sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option}
  elif [[ ${optionsPCHiC[@]} == *$option* ]]; then
    for cell in ${cellList[@]}
    do
      echo "sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option} ${cell}"
      sbatch -J ${option} ${sbatchopt}scriptDT.sh ${option} ${cell}
    done
  fi
}



run "$@";


## preprocessing
# scriptMain.sh splitBam
# scriptMain.sh prepBam
# scriptMain.sh prepPr
# scriptMain.sh prepEnh
# scriptMain.sh prepHiC


## DNA
# scriptMain.sh pDNA
# scriptMain.sh eDNA


## DNase
# scriptMain.sh genIndex
# scriptMain.sh bamToArray
# scriptMain.sh pgenProfile
# scriptMain.sh egenProfile


## Training Data
# scriptMain.sh hicMatch -n 13 : 21 min
# scriptMain.sh hicLabels : 9 hours


## Select Input Features for Training Data
# scriptMain selectDNase -n 30
# scriptMain selectDNA; task = split
# scriptMain selectDNA -n 100; task = run
# scriptMain selectDNA; task = combine

## Clean-Up
# find . -type f -regex ".*_[0-9]*\.npz*" | rm